/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hongpf' at '16-4-13 下午8:21' with Gradle 2.10
 *
 * @author hongpf, @date 16-4-13 下午8:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
